# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dimas-mufid',
                'doc_host': 'https://dimasmufid.github.io',
                'git_url': 'https://github.com/dimasmufid/dimas-mufid',
                'lib_path': 'dimas_mufid'},
  'syms': {'dimas_mufid.core': {'dimas_mufid.core.foo': ('core.html#foo', 'dimas_mufid/core.py')}}}
